spring.application.name=auth

server.port=${SERVER_PORT}
server.servlet.context-path=${SERVER_SERVLET_CONTEXT_PATH}


spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

logging.level.org.springframework.security=TRACE

spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD}
spring.data.redis.repositories.enabled=false

app.jwt.secret=${APP_JWT_SECRET}
app.jwt.expiration-ms=${APP_JWT_EXPIRATION_MS}

token.refresh.expiration-time-ms=${TOKEN_REFRESH_EXPIRATION_TIME_MS}

zalo.auth.auth-code-url=${ZALO_AUTH_CODE_URL}
zalo.auth.app-id=${ZALO_AUTH_APP_ID}
zalo.auth.redirect-uri=${ZALO_AUTH_REDIRECT_URI}
zalo.auth.code-verifier-time-ms=${ZALO_AUTH_CODE_VERIFIER_TIME_MS}
zalo.auth.access-token-url=${ZALO_AUTH_ACCESS_TOKEN_URL}
zalo.auth.khoa-bi-mat-cua-ung-dung=${ZALO_AUTH_KHOA_BI_MAT_CUA_UNG_DUNG}
zalo.auth.social-api-url=${ZALO_AUTH_SOCIAL_API_URL}

proxy.config.host-name=${PROXY_CONFIG_HOST_NAME}
proxy.config.port=${PROXY_CONFIG_PORT}

spring.mail.host=${SMTP_MAIL_HOST}
spring.mail.port=${SMTP_MAIL_PORT}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.username=${SMTP_USERNAME}
spring.mail.properties.mail.smtp.auth=${SMTP_AUTH_ENABLE}
spring.mail.properties.mail.smtp.starttls.enable=${SMTP_STARTTLS_ENABLE}
spring.mail.properties.mail.smtp.starttls.required=${SMTP_STARTTLS_REQUIRED}
spring.mail.properties[mail.smtp.connectiontimeout]=${SMTP_CONNECTION_TIMEOUT}
spring.mail.properties[mail.smtp.timeout]=${SMTP_TIMEOUT}
spring.mail.properties[mail.smtp.writetimeout]=${SMTP_WRITE_TIMEOUT}

service.email.address=${SERVICE_EMAIL_ADDRESS}

email.content.config.subject-templates.signup-otp=${SIGNUP_OTP_EMAIL_SUBJECT_TEMPLATE}
email.content.config.body-templates.signup-otp=${SIGNUP_OTP_EMAIL_BODY_TEMPLATE}

redirect.url.home-page=${REDIRECT_URL_HOMEPAGE}
redirect.url.problem-set-page=${REDIRECT_URL_PROBLEM_SET_PAGE}
server.forward-headers-strategy=${SERVER_FORWARD_HEADERS_STRATEGY}


management.server.port=${MANAGEMENT_SERVER_PORT}
management.endpoints.web.exposure.include=${ACTUATOR_WEB_EXPOSURE_INCLUDE}
management.metrics.tags.application=${spring.application.name}